[project]
name = "strava-datastack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.9.1",
    "dbt-duckdb>=1.9.1",
    "dlt[duckdb]>=1.3.0",
    "psutil>=6.1.1",
    "tqdm>=4.67.1",
]
